Repository pymc-labs/CausalPy, pull requests merged in 2023-09, with the labels that each got.

#232 Increase docstring coverage and add doctests
  .github/workflows/ci.yml
  CONTRIBUTING.md
  Makefile
  causalpy/custom_exceptions.py
  causalpy/data/datasets.py
  causalpy/data/simulate_data.py
  causalpy/plot_utils.py
  causalpy/pymc_experiments.py
  causalpy/pymc_models.py
  causalpy/skl_experiments.py
  causalpy/skl_models.py
  causalpy/tests/conftest.py
  causalpy/tests/test_data_loading.py
  causalpy/tests/test_input_validation.py
  causalpy/tests/test_integration_pymc_examples.py
  causalpy/tests/test_integration_skl_examples.py
  causalpy/tests/test_pymc_models.py
  causalpy/tests/test_utils.py
  causalpy/utils.py
  causalpy/version.py
  docs/source/_static/interrogate_badge.svg
  docs/source/examples.rst
  docs/source/index.rst
  pyproject.toml
Labels: documentation

#240 improve math rendering of pymc model docs
  causalpy/pymc_models.py
  pyproject.toml
Labels: documentation

#243 update website and email contact details from .io to .com domain
  README.md
Labels: documentation

#242 exclude dist folder from interrogate in `pyproject.toml`
  pyproject.toml
Labels: devops, no releasenotes

#244 bump to version 0.1.1
  causalpy/version.py
  pyproject.toml
Labels: no releasenotes
