Repository pymc-labs/CausalPy, pull requests merged in 2023-12, with the labels that each got.

#280 Ignore `causalpy/tests/` when running doctest to save a little time
  .github/workflows/ci.yml
  Makefile
Labels: devops

#275 changed splitting behaviour for PrePostFit
  causalpy/pymc_experiments.py
  causalpy/skl_experiments.py
Labels: bug

#272 User specified number of significant figures for numbers in plots
  causalpy/pymc_experiments.py
  causalpy/skl_experiments.py
  causalpy/tests/test_utils.py
  causalpy/utils.py
  docs/source/_static/interrogate_badge.svg
  docs/source/notebooks/did_pymc.ipynb
  docs/source/notebooks/did_pymc_banks.ipynb
  docs/source/notebooks/its_pymc.ipynb
  docs/source/notebooks/its_skl.ipynb
  docs/source/notebooks/rd_pymc.ipynb
  docs/source/notebooks/rd_pymc_drinking.ipynb
  docs/source/notebooks/rd_skl.ipynb
  docs/source/notebooks/rd_skl_drinking.ipynb
  docs/source/notebooks/sc_pymc.ipynb
Labels: enhancement
