Repository pymc-labs/CausalPy, pull requests merged in 2023-10, with the labels that each got.

#247 fix PrePostNEGD input validation
  causalpy/pymc_experiments.py
Labels: enhancement

#258 Fix error in plot method
  causalpy/pymc_experiments.py
  causalpy/tests/test_pymc_experiments.py
  docs/source/_static/interrogate_badge.svg
Labels: bug, plotting

#260 update README
  README.md
Labels: documentation

#263 Version bump
  causalpy/version.py
  pyproject.toml
Labels: no releasenotes
