Repository pymc-labs/CausalPy, pull requests merged in 2023-11, with the labels that each got.

#268 Adopt Ruff linter and formatter
  .pre-commit-config.yaml
  README.md
  causalpy/__init__.py
  docs/source/notebooks/did_skl.ipynb
  docs/source/notebooks/geolift1.ipynb
  pyproject.toml
  setup.cfg
Labels: devops, no releasenotes

#264 Add ability to analyse Regression Kink Analysis Designs
  .pre-commit-config.yaml
  README.md
  causalpy/pymc_experiments.py
  causalpy/tests/test_input_validation.py
  causalpy/tests/test_integration_pymc_examples.py
  causalpy/tests/test_pymc_experiments.py
  docs/source/_static/classes.png
  docs/source/_static/interrogate_badge.svg
  docs/source/_static/packages.png
  docs/source/_static/regression_kink_pymc.svg
  docs/source/examples.rst
  docs/source/glossary.rst
  docs/source/index.rst
  docs/source/notebooks/generate_plots.ipynb
  docs/source/notebooks/rkink_pymc.ipynb
Labels: enhancement

#269 version bump to 0.2.0
  causalpy/version.py
  pyproject.toml
Labels: no releasenotes

#274 Replace makefile commands with ruff
  Makefile
  causalpy/__init__.py
  causalpy/pymc_experiments.py
  causalpy/tests/test_input_validation.py
  pyproject.toml
Labels: devops, no releasenotes
