Repository pymc-labs/CausalPy, pull requests merged in 2024-03, with the labels that each got.

#291 Fix #288: remove deprecated 'model' property in tests.
  causalpy/pymc_models.py
Labels: bug

#296 Fix causal impact calculation error in synthetic control and interrupted time series
  causalpy/pymc_experiments.py
  docs/source/notebooks/geolift1.ipynb
  docs/source/notebooks/its_covid.ipynb
  docs/source/notebooks/its_pymc.ipynb
  docs/source/notebooks/sc_pymc.ipynb
  docs/source/notebooks/sc_pymc_brexit.ipynb
Labels: bug

#298 version bump to 0.2.2
  causalpy/version.py
  pyproject.toml
Labels: no releasenotes

#310 Upload versions due to Node 16 sunset.
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: devops

#307 Fix #210: Add scikit-learn plots to README.
  README.md
  docs/source/_static/interrupted_time_series_skl.svg
  docs/source/notebooks/generate_plots.ipynb
Labels: documentation
