Repository pymc-labs/CausalPy, pull requests merged in 2024-06, with the labels that each got.

#347 Add support for Python 3.12
  .github/workflows/ci.yml
  .github/workflows/release.yml
  pyproject.toml
Labels: enhancement

#349 Update `codecov-action@v3` to `v4`
  .github/workflows/ci.yml
Labels: devops

#351 Simplify remote GitHub actions by building test environment only once
  .github/workflows/ci.yml
Labels: devops

#352 Fix up ruff pre-commit checks to operate on notebooks
  .pre-commit-config.yaml
  docs/source/notebooks/did_pymc_banks.ipynb
  docs/source/notebooks/did_skl.ipynb
  docs/source/notebooks/generate_plots.ipynb
  docs/source/notebooks/its_skl.ipynb
  docs/source/notebooks/rd_pymc_drinking.ipynb
  docs/source/notebooks/rd_skl.ipynb
  docs/source/quasi_dags.ipynb
Labels: devops

#353 Remove all remaining traces of `nbqa` from the repo
  Makefile
  pyproject.toml
Labels: devops

#354 Various improvements to documentation infrastructure
  .github/workflows/rtd-link-preview.yml
  .gitignore
  .readthedocs.yaml
  README.md
  docs/source/conf.py
  docs/source/index.rst
  pyproject.toml
Labels: documentation

#355 Enable `summary` method for all currently implemented frequentist experiments
  causalpy/pymc_experiments.py
  causalpy/skl_experiments.py
  causalpy/tests/test_integration_skl_examples.py
  docs/source/_static/classes.png
  docs/source/_static/interrogate_badge.svg
  docs/source/_static/packages.png
  docs/source/notebooks/did_skl.ipynb
  docs/source/notebooks/its_skl.ipynb
  docs/source/notebooks/rd_skl.ipynb
  docs/source/notebooks/rd_skl_drinking.ipynb
  docs/source/notebooks/sc_skl.ipynb
Labels: documentation, enhancement, outputs

#359 Improve formatting of model coefficients in `summary` method in pymc-based experiments
  causalpy/pymc_experiments.py
  causalpy/tests/test_integration_pymc_examples.py
  docs/source/notebooks/ancova_pymc.ipynb
  docs/source/notebooks/did_pymc.ipynb
  docs/source/notebooks/did_pymc_banks.ipynb
  docs/source/notebooks/its_pymc.ipynb
  docs/source/notebooks/rd_pymc.ipynb
  docs/source/notebooks/rd_pymc_drinking.ipynb
  docs/source/notebooks/rkink_pymc.ipynb
  docs/source/notebooks/sc_pymc.ipynb
  docs/source/notebooks/sc_pymc_brexit.ipynb
Labels: enhancement

#363 bump to version 0.3.1
  causalpy/version.py
  pyproject.toml
Labels: no releasenotes

#338 Add example analysis of multiple geo lift test analysis
  causalpy/data/datasets.py
  causalpy/data/geolift_multi_cell.csv
  causalpy/data/simulate_data.py
  causalpy/tests/test_synthetic_data.py
  docs/source/_static/interrogate_badge.svg
  docs/source/examples.rst
  docs/source/notebooks/multi_cell_geolift.ipynb
  pyproject.toml
Labels: documentation, enhancement

#377 Fix typo in docs
  docs/source/index.md
Labels: documentation, no releasenotes

#379 Add page of causal video resources from PyMC community into the docs
  docs/source/knowledgebase/causal_video_resources.md
  docs/source/knowledgebase/index.md
Labels: documentation
