Repository pymc-labs/CausalPy, pull requests merged in 2024-04, with the labels that each got.

#313 Drop support for Python 3.8 and 3.9, add 3.11
  .github/workflows/ci.yml
  .github/workflows/release.yml
  CONTRIBUTING.md
  pyproject.toml
Labels: devops

#312 Add experiment design notation docs page to new Knowledge Base section of the docs
  docs/source/design_notation.md
  docs/source/glossary.rst
  docs/source/index.rst
  docs/source/references.bib
Labels: documentation

#314 bump version to 0.2.3
  causalpy/version.py
  pyproject.toml
Labels: no releasenotes

#316 Revert the GitHub Actions update due to Node 16 sunset.
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: devops
