Repository pymc-labs/CausalPy, pull requests merged in 2024-05, with the labels that each got.

#322 Automate pre commit updates
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .pre-commit-config.yaml
  causalpy/data/__init__.py
  causalpy/data/datasets.py
  causalpy/data/simulate_data.py
  causalpy/skl_experiments.py
  causalpy/skl_models.py
  causalpy/tests/conftest.py
  causalpy/tests/test_data_loading.py
  causalpy/utils.py
Labels: devops

#325 Fix `FutureError` warning, which requires `pymc>=5.14.0`
  causalpy/pymc_models.py
  causalpy/tests/test_pymc_models.py
  pyproject.toml
Labels: bug

#321 Add new knowledge base page on causal DAGS for quasi-experiments
  docs/source/glossary.rst
  docs/source/index.rst
  docs/source/quasi_dags.ipynb
  docs/source/references.bib
  pyproject.toml
Labels: documentation

#328 Add license
  .pre-commit-config.yaml
  causalpy/__init__.py
  causalpy/custom_exceptions.py
  causalpy/data/__init__.py
  causalpy/data/datasets.py
  causalpy/data/simulate_data.py
  causalpy/data_validation.py
  causalpy/plot_utils.py
  causalpy/pymc_experiments.py
  causalpy/pymc_models.py
  causalpy/skl_experiments.py
  causalpy/skl_models.py
  causalpy/tests/__init__.py
  causalpy/tests/conftest.py
  causalpy/tests/test_data_loading.py
  causalpy/tests/test_input_validation.py
  causalpy/tests/test_integration_pymc_examples.py
  causalpy/tests/test_integration_skl_examples.py
  causalpy/tests/test_pymc_experiments.py
  causalpy/tests/test_pymc_models.py
  causalpy/tests/test_utils.py
  causalpy/utils.py
  causalpy/version.py
Labels: devops, no releasenotes

#332 Bound MyST NB to fix the compressed images.
  pyproject.toml
Labels: documentation, devops, no releasenotes

#304 Move to a conda only install of pymc
  CONTRIBUTING.md
  Makefile
  docs/source/notebooks/did_pymc.ipynb
  docs/source/notebooks/did_pymc_banks.ipynb
  docs/source/notebooks/geolift1.ipynb
  docs/source/notebooks/its_covid.ipynb
  docs/source/notebooks/its_pymc.ipynb
  docs/source/notebooks/rd_pymc.ipynb
  docs/source/notebooks/rd_pymc_drinking.ipynb
  docs/source/notebooks/rkink_pymc.ipynb
  docs/source/notebooks/sc_pymc.ipynb
  docs/source/notebooks/sc_pymc_brexit.ipynb
  environment.yml
Labels: devops

#339 bump version to 0.3.0
  causalpy/version.py
  pyproject.toml
Labels: no releasenotes
