Repository pymc-labs/CausalPy, pull requests merged in 2025-05, with the labels that each got.

#447 Add new list of written learning resources to the docs
  README.md
  docs/source/knowledgebase/causal_written_resources.md
  docs/source/knowledgebase/index.md
Labels: documentation

#471 Auto-label pre-commit autoupdate PRs with "no releasenotes"
  .github/workflows/label-precommit-prs.yml
Labels: devops

#477 Bump version to 0.4.2
  causalpy/version.py
  pyproject.toml
Labels: no releasenotes
