Repository pymc-labs/CausalPy, pull requests merged in 2025-04, with the labels that each got.

#446 fixes for uml github action
  .github/workflows/uml.yml
  pyproject.toml
Labels: devops

#438 Get plot data for prepostfit experiments
  causalpy/experiments/base.py
  causalpy/experiments/diff_in_diff.py
  causalpy/experiments/prepostfit.py
  causalpy/experiments/prepostnegd.py
  causalpy/experiments/regression_discontinuity.py
  causalpy/experiments/regression_kink.py
  causalpy/plot_utils.py
  causalpy/tests/test_integration_pymc_examples.py
  causalpy/tests/test_integration_skl_examples.py
  docs/source/_static/classes.png
  docs/source/_static/interrogate_badge.svg
  docs/source/_static/packages.png
  docs/source/conf.py
Labels: enhancement

#455 Replaced `MutableData` with `Data`
  causalpy/pymc_models.py
Labels: bug

#458 Separate `InterruptedTimeSeries` and `SyntheticControl` classes, update uml
  causalpy/__init__.py
  causalpy/experiments/base.py
  causalpy/experiments/interrupted_time_series.py
  causalpy/experiments/synthetic_control.py
  causalpy/pymc_experiments.py
  causalpy/skl_experiments.py
  causalpy/tests/test_api_stability.py
  docs/source/_static/classes.png
  docs/source/_static/interrogate_badge.svg
  docs/source/_static/packages.png
Labels: refactor

#462 fix bug: obs_indx -> obs_ind and improve `PyMCModel._data_setter`
  causalpy/experiments/diff_in_diff.py
  causalpy/experiments/interrupted_time_series.py
  causalpy/experiments/prepostnegd.py
  causalpy/experiments/regression_discontinuity.py
  causalpy/experiments/regression_kink.py
  causalpy/experiments/synthetic_control.py
  causalpy/pymc_models.py
Labels: bug

#465 Update badges on GitHub landing page
  README.md
Labels: documentation
