Repository pymc-labs/CausalPy, pull requests merged in 2025-07, with the labels that each got.

#489 Use mock sample in tests
  .github/workflows/ci.yml
  Makefile
  causalpy/experiments/prepostnegd.py
  causalpy/tests/conftest.py
  causalpy/tests/test_integration_pymc_examples.py
  causalpy/tests/test_pymc_models.py
  pyproject.toml
Labels: no releasenotes

#501 Interrupted time series docs - more explanation and info on extracting causal impact measures
  docs/source/notebooks/its_pymc.ipynb
Labels: documentation

#505 Fix to minor bug in simulated data generation function
  causalpy/data/simulate_data.py
Labels: bug
